name: pre-commit-autoupdate

on:
  schedule:
    # Tuesday at 18:00 UTC
    - cron: '0 18 * * 2'

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update pre-commit hooks
        uses: ./
        with:
          gh-token: ${{ secrets.COATL_BOT_GH_TOKEN }}
